SELECT DISTINCT
    CONSUMER_APPLICATION_NUMBER,
    CONSUMER_NAME,
    ADDRESS,
    CREATED_DATE,
    APPLICATION_STATUS,
    SHORT_DESCRIPTION_OF_WORK,
    NATURE_OF_WORK_ID,
    PREMISE_AREA_TYPE
FROM {{ref('stg_consumer_application_detail')}}