SELECT
    CONSUMER_APPLICATION_NO AS CONSUMER_APPLICATION_NUMBER,
    TRANSACTION_DATE,
    MOBILE_NO,
    REG_AMOUNT,
    PAYMENT_METHOD_TYPE,
    ADDITIONAL_INFO1,
    CHARGE_AMOUNT
FROM {{ref('stg_billdesk_payment_res')}}