SELECT
  CONS_APP_NO AS CONSUMER_APPLICATION_NUMBER,
    SUPERVISION_AMNT,
    ESTIMATE_AMOUNT,
    CGST,
    SGST,
    AMOUNT_TO_PAY,
    LOCATION,
    DEPOSIT_AMT,
    APPROVED_BY,
    CREATE_DATE
FROM {{ref('stg_erp_rev')}}