name: dbt CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  dbt-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dbt
        run: |
          pip install dbt-snowflake

      - name: Check dbt
        run: |
          dbt --version

      - name: Install dependencies
        run: |
          dbt deps

      - name: Parse dbt project
        run: |
          dbt parse